### ISSUE TITLE
Source maps

### ISSUE THREAD

**Issue by kendagriff** [magnars/optimus#58]
Any suggestions for delivering a source map? At the end of the bundle.js file there is

```
//# sourceMappingURL=bundle.js.map
```

But, of course, that file can't be found at /token/bundle.js.map. Any ideas?

**Comment by magnars** [comment]
What is creating these source maps?
man. 15. mai 2017 kl. 22.04 skrev Kendall Buchanan <notifications@github.com

**Comment by kendagriff** [comment]
The map is output from a webpack bundle. So, yeah, not the result of any combined files in optimus...

**Comment by magnars** [comment]
Okay, so you just want to serve it via optimus? You can use regex in `load-assets`. Something like this?

```
(defn get-assets []
  (concat
   ;; ...
   (assets/load-assets "public" [#"/token/.+\.js\.map"])))
```

**Comment by kendagriff** [comment]
I should have clarified that bundle.js is being served by Optimus with a
cache busting URL (e.g. /cache-busting-hash/bundle.js).

How can the source map share the same directory, so it can be retrieved
relative to bundle.js?

**Comment by magnars** [comment]
In this case, you will have to do a bit of coding yourself. :) 

Remember, the assets are just data. They are a seq of maps: `[{:path :contents}]`. Write your own "optimization" that looks for `sourceMappingURL` and fixes it. 

There's more info on this here: https://github.com/magnars/optimus#what-are-these-assets-anyway-they-seem-magical-to-me

**Comment by kendagriff** [comment]
Makes sense! Thank you, thank you.
