### ISSUE TITLE
Content Encoding

### ISSUE THREAD

**Issue by kendagriff** [magnars/optimus#62]
Quick question: I have some precompressed (gzipped) javascript assets I'd like to serve via Optimus, however, they need "Content-Encoding: gzip" attached as a response header.

Any suggestion for how to accomplish that?

**Comment by magnars** [comment]
Optimus assets are just maps, and :headers is one of the fields. You can
assoc your headers there. See how long expiry headers are added by Optimus
itself.
tor. 11. jan. 2018 kl. 19:04 skrev Kendall Buchanan <
notifications@github.com>:

**Comment by kendagriff** [comment]
Awesome! Thanks for the tip.
